esphome:
  name: rf1c
  friendly_name: RF1C
  on_boot:
    then:
      - globals.set:
          id: data_was_restored
          value: 'true'
      - pulse_meter.set_total_pulses:
          id: sensor_pulse_meter
          value: !lambda 'return id(pulses);'

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: None

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

preferences:
  flash_write_interval: 6h

web_server:
  port: 80

globals:
  - id: pulses
    type: int
    restore_value: yes
    initial_value: '0'
  - id: data_was_restored
    type: bool
    initial_value: "0"

sensor:
  - platform: pulse_meter
    id: sensor_pulse_meter
    name: Gas Pulse
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
    internal_filter: 100ms
    device_class: gas
    unit_of_measurement: "m³/min"
    icon: "mdi:fire"
    accuracy_decimals: 3
    filters:
      - multiply: 0.01
    total:
      id: sensor_pulse_meter_total
      name: "Gas"
      filters:
        - multiply: 0.01
      unit_of_measurement: "m³"
      state_class: total_increasing
      icon: "mdi:fire"
      accuracy_decimals: 3
      on_raw_value:
        then:
          - if:
              # This avoids overriding the pulses global before the value is restored by on_boot
              condition:
                lambda: 'return id(data_was_restored);'
              then:
                - lambda: 'id(pulses) = x;'
  - platform: homeassistant
    name: Offset Gas
    entity_id: sensor.meter_rf1c_offset
    id: offset
    on_value:
      then:
        - pulse_meter.set_total_pulses:
            id: sensor_pulse_meter
            value: !lambda 'return int(x);'

  - platform: uptime
    name: Uptime Sensor

  - platform: wifi_signal
    name: "WiFi Signal Sensor"

  - platform: internal_temperature
    name: "Internal Temperature"

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    hide_hash: true
