substitutions:
  devicename: shelly25_evgeni
  location: Evgeni
  open_duration: 17sec
  open_switch: switch1
  open_relay: relay2
  open_sensor: current_b
  open_time: '0 0 7 * * *'
  open_time_2: '0 0 7 * * *'
  close_duration: 16sec
  close_switch: switch2
  close_relay: relay1
  close_sensor: current_a
  <<: !include _shelly25-pins.yaml

<<: !include shelly25.yaml
