substitutions:
  devicename: shelly25_kitchen
  location: Kitchen
  open_duration: 17sec
  open_switch: switch2
  open_relay: relay1
  open_sensor: current_a
  open_time: '0 0 6 * * *'
  open_time_2: '0 0 6 * * *'
  close_duration: 16sec
  close_switch: switch1
  close_relay: relay2
  close_sensor: current_b
  <<: !include _shelly25-pins.yaml

<<: !include _shelly25.yaml
