substitutions:
  devicename: shelly25_janine
  location: Janine
  open_duration: 28sec
  open_switch: switch1
  open_relay: relay2
  open_time: '0 0 7 * * *'
  close_duration: 26sec
  close_switch: switch2
  close_relay: relay1
  <<: !include shelly25-pins.yaml

<<: !include shelly25.yaml
