name: CI

on:
  push:
    branches:
      - devel
    tags:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  data:
    runs-on: ubuntu-22.04
    outputs:
      python: ${{ steps.python.outputs.python }}
      targets: ${{ steps.targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y jo
      - name: Find Python version
        id: python
        run: echo "python=$(grep python_version Pipfile | cut -d= -f 2 | tr -d '\" ')" >> "$GITHUB_OUTPUT"
      - name: Find compile targets
        id: targets
        run: echo "targets=$(jo -a $(make targets))" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-22.04
    needs: data
    strategy:
      matrix:
        target: ${{ fromJson(needs.data.outputs.targets) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.data.outputs.python }}
      - run: cp somfy_secrets.h.example somfy_secrets.h
      - run: cp secrets.yaml.example secrets.yaml
      - run: pip install pipenv
      - run: pipenv sync
      - run: pipenv run esphome compile ${{ matrix.target }}
